Add LineChart component
tum-v2/parloa-ui pull request #10
Opened 2023-11-20 16:41 UTC by GLDuval

This PR adds a basic implementation of a LineChart Component that supports multiple lines and datapoints. In order to use Antd's theme values `'use client'` had to be added at the start of the page (this will be removed once we find a solution).

<img width="983" alt="image" src="https://github.com/tum-v2/parloa-ui/assets/46896242/e0efb08c-85df-4c9f-bc14-dab6c64a4458">

2023-11-20 17:43 UTC, GLDuval commented
Will wait until we fix our theme situation to merge.

2023-11-22 08:48 UTC, robynkoelle requested changes

2023-11-22 08:48 UTC, robynkoelle commented on src/components/charts/LineChart.tsx
> +  width: number;
Should we make the dimensions optional, so that by default it fills the space it needs?

2023-11-22 08:48 UTC, robynkoelle commented on src/components/charts/LineChart.tsx
> +  padding = 50,
Use theme

2023-11-22 08:48 UTC, robynkoelle commented on src/components/charts/LineChart.tsx
> +        rx={14}
Either remove or use theme values

2023-11-22 08:48 UTC, robynkoelle commented on src/theme/theme.ts
> +    textDescription: 'rgba(36, 19, 43, 0.45)'
I would name the colors by the color they are. For example, now we are using color.textDescription for the chart line, which is confusing

2023-11-22 08:48 UTC, robynkoelle commented on src/components/charts/LineChart.tsx
> +  xMin,
Should we set this automatically depending on the given data?

2023-11-22 08:48 UTC, robynkoelle commented on src/components/charts/LineChart.tsx
> +  yUnit
I would make this optional, and show just the numbers (like on the x axis) by default

2023-11-22 08:48 UTC, robynkoelle commented on src/components/charts/LineChart.tsx
> +            from={theme.chartColors[i]}
I would define the chartColors array in this component, add the individual colors to theme.colors, and remove theme.chartColors

2023-11-22 08:48 UTC, robynkoelle commented on src/components/charts/LineChart.tsx
> +            strokeWidth={3}
I would add this to the theme, e.g. `theme.lineWidth.m`. We could re-use this property for the borders of our cards etc.

2023-11-22 09:02 UTC, GLDuval commented on src/components/charts/LineChart.tsx
> +  yUnit
It's optional already

2023-11-22 09:35 UTC, GLDuval commented on src/components/charts/LineChart.tsx
> +  xMin,
xMax, xMin, yMax are all set automatically now

2023-11-22 10:03 UTC, robynkoelle approved these changes

2023-11-22 10:05 UTC, merged