Feature/par 110 uiux add navbar to main layout
tum-v2/parloa-ui pull request #15
Opened 2023-11-22 11:02 UTC by guid3d

https://github.com/tum-v2/parloa-ui/assets/29707419/b9634c78-11c1-407a-8166-e460e32bd360

- Add NavBar to main layout
- Route each button to each pages

2023-11-23 11:06 UTC, robynkoelle requested changes

2023-11-23 11:06 UTC, robynkoelle commented on src/components/nav-bar/index.tsx
> +            router.push('/login');
Add a // TODO here

2023-11-23 11:06 UTC, robynkoelle commented on src/components/nav-bar/index.tsx
> +    backgroundColor: 'white'
Use theme

2023-11-23 11:06 UTC, robynkoelle commented on src/components/nav-bar/components/NavBarTab.tsx
> +          router.push(`/${selectedTab.toLowerCase()}`);
As a developer I would not expect the values of the NavBarTabOptions enum to affect the path that is called when I click on a navigation bar item. I would write a function that explicitly maps a NavBarTabOption to a path.

2023-11-23 11:06 UTC, robynkoelle commented on src/app/dashboard/page.tsx
Good for testing, but please remove the hundreds of lines before merging

2023-11-23 11:06 UTC, robynkoelle commented on src/app/page.tsx
Good for testing, but please remove the hundreds of lines before merging

2023-11-23 21:24 UTC, guid3d commented on src/components/nav-bar/components/NavBarTab.tsx
> +          router.push(`/${selectedTab.toLowerCase()}`);
What do you mean by this? We don't use the router.push? You mean the url path stay the same when changing the tab?

2023-11-24 12:54 UTC, GLDuval commented on src/components/nav-bar/components/NavBarTab.tsx
> +          router.push(`/${selectedTab.toLowerCase()}`);
Instead of having an enum we could also have an array of NavbarTabOption objects type with `name` and `path` properties.

2023-11-24 16:01 UTC, guid3d commented on src/components/nav-bar/components/NavBarTab.tsx
> +          router.push(`/${selectedTab.toLowerCase()}`);
I changed it the different way, but check it out, it's cleaner

2023-11-24 16:25 UTC, GLDuval commented on src/app/page.tsx
> +      <div>Hi!</div>
Please remove these unnecessary Hi! Also there is an unused import causing a lint error at the top of the file.

2023-11-24 16:25 UTC, GLDuval commented on src/components/nav-bar/index.tsx
> +        <Image src={logo} alt="logo" width={36} height={36} priority={false} />
Use logo sizes from theme

2023-11-26 11:15 UTC, robynkoelle requested changes

2023-11-26 11:15 UTC, robynkoelle commented on src/components/nav-bar/index.tsx
> +  const [selectedTab, setSelectedTab] = useState<string>('dashboard');
Use the enum

2023-11-26 11:15 UTC, robynkoelle commented on src/components/nav-bar/components/NavBarTab.tsx
> +    textTransform: 'capitalize'
I see the navigation bar options (textual descriptions) and routes as two different things, and I would explicitly distinguish them. With this approach, we are using the routes, and just capitalizing them. I would use either Gabriel's or my approach (see previous comments in this PR)

2023-11-26 11:15 UTC, robynkoelle commented on src/theme/theme.ts
> +    navbarLogoSize: 36
I don't think we need this as a global theme property, since it only affects the navigation bar

2023-11-26 11:20 UTC, guid3d commented on src/theme/theme.ts
> +    navbarLogoSize: 36
Guys, can you decide on one way. Gabriel says one thing aand you say one thing

2023-11-26 11:59 UTC, robynkoelle commented on src/theme/theme.ts
> +    navbarLogoSize: 36
Just made an announcement to the team chat 👍

2023-11-26 12:06 UTC, GLDuval commented on src/theme/theme.ts
> +    navbarLogoSize: 36
My comment was mostly to say to use our existing sizings instead of creating a new one, but if none of them work well with our navbar design then we can just keep it in the navbar component file it's fine with me :)

2023-11-26 12:26 UTC, guid3d commented on src/theme/theme.ts
> +    navbarLogoSize: 36
I'm sorry. I just want to finally merge this 😭

2023-11-26 12:41 UTC, GLDuval commented on src/theme/theme.ts
> +    navbarLogoSize: 36
Hahaha same we need to get this moving

2023-11-26 13:20 UTC, GLDuval submitted a review, later dismissed

2023-11-26 13:59 UTC, guid3d commented on src/components/nav-bar/components/NavBarTab.tsx
> +          router.push(`/${selectedTab.toLowerCase()}`);
Can you guys help me think the better way to handle this, I did make it better by checking right away whether it is enum NavBarOptions or not. But still I couldn't think of the other way 🥲

2023-11-26 16:41 UTC, GLDuval commented on src/components/nav-bar/components/NavBarTab.tsx
> +          router.push(`/${selectedTab.toLowerCase()}`);
My idea was having a NavbarOption type with name and route properties that you declare in the NavBar component. So you would then use this new type instead of string for you selectedTab and setSelectedTab props.

2023-11-26 16:42 UTC, GLDuval commented on src/components/nav-bar/components/NavBarTab.tsx
> +          router.push(`/${selectedTab.toLowerCase()}`);
Personally I don't really like working with enums in Typescript they don't really work well most of the time 😅

2023-11-28 17:23 UTC, merged