Feature/par 163 uiux set up state management for create simulation
tum-v2/parloa-ui pull request #32
Opened 2023-12-03 15:26 UTC by Sathwik-Amburi

Added statemanagement and validation. Connection to backend is pending but can done in the SimulationModal.tsx file in the handleFinish Function. 

![Screenshot from 2023-12-03 16-24-29](https://github.com/tum-v2/parloa-ui/assets/43044722/62fd5b2d-e360-4c4c-a125-a76d763464f7)

Note: Prompt, Scenario type and everything related that is pending, need to discuss after the Customer meeting how to design those.

2023-12-05 09:37 UTC, guid3d requested changes

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/Steps/SimulationScenarioStep.tsx
> +    >
Use Flex from AntD like how Gabriel used it

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/Steps/SimulationSelection.tsx
> +    <div style={{ display: 'flex' }}>
Use Flex from AntD

2023-12-05 09:37 UTC, guid3d commented on src/store/features/CreateSimulation/CreateSimulationSlice.ts
> +  type: 'AUTOMATED' | 'MANUAL' | 'OPTIMIZATION' | 'A/B TESTING' | '';
extract this out as a dedicated type so it can be reused again down there

2023-12-05 09:37 UTC, guid3d commented on src/store/features/CreateSimulation/CreateSimulationSlice.ts
> +        'AUTOMATED' | 'MANUAL' | 'OPTIMIZATION' | 'A/B TESTING' | ''
reuse the one we create above here

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/ModelCard.tsx
> +            onClick={() => onButtonClick()}
The old way doesn't work? I just wonder as I always just do `onClick={onButtonClick}`

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/SimulationCard.tsx
> +    if (simulation.type === mode.toUpperCase()) {
Maybe change mode to global enum in one file and we can import to use like `Mode.Manual` `Mode.Automated`

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/SimulationCard.tsx
> +    if (mode === 'manual') {
This case as well, instead of directly type string `manual` we import already created enum and `Mode.Manual`

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/SimulationCard.tsx
> +      }
Same here, use enum

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/Steps/SimulationAgentStep.tsx
> +      case 'automated':
Same here, use enum

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/Steps/SimulationAgentStep.tsx
> +                {mode === 'automated' ? (
Same here, use enum

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/Steps/SimulationAgentStep.tsx
> +      case 'manual':
Same here, use enum

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/Steps/SimulationNameStep.tsx
> +  const [mode, setMode] = React.useState<'manual' | 'automated'>('manual');
Extract the type out : `type Mode = 'manual' | 'automated` as we share the same type in many files and just import it

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/Steps/SimulationNameStep.tsx
> +    if (simulation.type === 'MANUAL') {
Same here, use enum

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/Steps/SimulationNameStep.tsx
> +    <div
Use AntD Flex like Gabriel

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/Steps/SimulationNameStep.tsx
If it's not too much work, tryout this https://ant.design/components/form
I found it quite nice in term of form validation, required field, etc.
It also comes with padding for label integrated

2023-12-05 09:37 UTC, guid3d commented on src/components/simulation-modal/Steps/SimulationScenarioStep.tsx
Same here, may be take a look at AntD Form

2023-12-16 12:45 UTC, GLDuval approved these changes

2023-12-16 12:45 UTC, merged