Feature/par 81 uiux create navbar
tum-v2/parloa-ui pull request #7
Opened 2023-11-20 11:30 UTC by guid3d

<img width="969" alt="Screenshot 2023-11-20 at 12 28 35" src="https://github.com/tum-v2/parloa-ui/assets/29707419/0421c780-9430-415f-a28a-233a43435b53">

I use the "Segment" component from AntD and it needs to be configured to be used as NavBar. That's why the style is hardcoded in in component not in the theme (as I don't want to change the default style of "Segment"

2023-11-21 07:25 UTC, GLDuval commented on src/components/generic/NavBar/components/NavBarTab.tsx
> +            itemSelectedBg: '#F7F4F9'
Should add this color string to `theme.ts` if it's not already there, and import it into this file.

2023-11-21 07:30 UTC, GLDuval commented on src/components/generic/NavBar/components/NavBarLogout.tsx
> +const NavBarLogout: React.FC<NavBarLogoutProps> = ({ onClick, isLoading }) => {
We decided to not use `React.FC` so you can just do this instead.
```suggestion
const NavBarLogout = ({ onClick, isLoading }: NavBarLogoutProps) => {
```

2023-11-21 07:30 UTC, GLDuval commented on src/components/generic/NavBar/components/NavBarTab.tsx
> +const NavBarTab: React.FC<NavBarTabProps> = ({
Remove `React.FC` here also

2023-11-22 09:01 UTC, Sathwik-Amburi approved these changes
Looks good now!

2023-11-22 09:19 UTC, robynkoelle requested changes

2023-11-22 09:19 UTC, robynkoelle commented on src/app/page.tsx
> +      <NavBar> </NavBar>
```suggestion
      <NavBar/>
```

2023-11-22 09:19 UTC, robynkoelle commented on src/components/generic/NavBar/components/NavBarLogout.tsx
Not a generic component, so I would not put it under generic

2023-11-22 09:19 UTC, robynkoelle commented on src/components/generic/NavBar/components/NavBarLogout.tsx
>      padding: 4,
Use theme

2023-11-22 09:19 UTC, robynkoelle commented on src/components/generic/NavBar/components/NavBarTab.tsx
>      padding: 4,
Use theme

2023-11-22 09:19 UTC, robynkoelle commented on src/theme/theme.ts
> +    colorSelectedNavBar: '#F7F4F9'
I would name it after the color, not how the color is used. And add it to theme.color instead of theme.token

2023-11-22 09:19 UTC, robynkoelle commented on src/components/generic/NavBar/components/NavBarTab.tsx
>        theme={{
Add a comment why this is necessary

2023-11-22 09:52 UTC, Sathwik-Amburi submitted a review, later dismissed
Looks good!

2023-11-22 10:08 UTC, robynkoelle submitted a review, later dismissed

2023-11-22 10:11 UTC, robynkoelle approved these changes

2023-11-22 10:11 UTC, merged